components:
  parameters:
    Id:
      name: id
      in: path
      required: true
      schema:
        type: integer
        minimum: 1
    Limit:
      name: limit
      in: query
      required: true
      schema:
        type: integer
        minimum: 1
        maximum: 1000
        default: 1000
    Offset:
      name: offset
      in: query
      required: true
      schema:
        type: integer
        minimum: 0
        default: 0
    Order:
      name: order
      in: query
      required: true
      description: 'field for sort list, for DESC sort you need to put "-" before the field name, for example: "-id", sorting will be performed in the order of fields'
      schema:
        type: array
        items:
          type: string
        default: ["id"]
    Keys:
      name: keys
      in: query
      required: true
      schema:
        type: array
        items:
          type: string
