language: node_js
node_js:
  - "12"

services:
  - postgresql


env:
  - DB_HOST="localhost" DB_PORT="5432" DB_DIALECT="postgres" DB_POOL_MAX="1" DB_POOL_MIN="1" DB_NAME="travis_ci_test" DB_USER="postgres" DB_PASSWORD="" ADMIN_SALT="asdvndosnnsdvasdfw3tfgsdavijnv" ADMIN_JWT_KEY="3223C23WEFCZDVAFsdsfsdfg" USER_SALT="asdvndosnnsdivgzcxvxcvwesZXzvcadcasdjnv" USER_JWT_KEY="asdvnddafscvzcvdfcosnnsdijnv"

install:
  - yarn install

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - yarn test