/products:
  get: 
    operationId: user/ProductController.list
    tags:
    - product 
    parameters: 
      - name: brandId
        type: integer
        in: query 
        schema:
          type: integer
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Order'
    responses:
      '200':  {$ref: '#/components/responses/ListProduct'}
      default: {$ref: '#/components/responses/GenericError'}

/products/{id}:
  get:
    tags:
    - product 
    operationId: user/ProductController.get
    parameters:
      - $ref: '#/components/parameters/Id'
    responses:
      '200':  {$ref: '#/components/responses/OneProduct'}
      default: {$ref: '#/components/responses/GenericError'}
