/products:
  get: 
    operationId: user/ProductController.list
    tags:
    - product 
    parameters: 
      - name: brand
        schema:
          type: integer
        required: false
        in: query
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset' 
    responses:
      '200':  {$ref: '#/components/responses/ListProduct'}
      default: {$ref: '#/components/responses/GenericError'}

/product/{id}:
  get:
    tags:
    - product 
    operationId: user/ProductController.get
    parameters:
      - in: path
        name: id
        description: Track ID.
        required: true
        schema:
          type: integer
    responses:
      '200':  {$ref: '#/components/responses/OneProduct'}
      default: {$ref: '#/components/responses/GenericError'}
