/admin/products:
  get: 
    security: 
      - apiKey: [] 
    operationId: admin/ProductController.list
    tags:
    - product 
    parameters: 
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Order'
      - name: brandId 
        in: query
        schema:
          type: integer
    responses:
      '200':  {$ref: '#/components/responses/ListProduct'}
      default: {$ref: '#/components/responses/GenericError'} 
  post:
    security: 
      - apiKey: [] 
    description: "Create new product"
    operationId: admin/ProductController.create
    tags:
    - product  
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductCreate'
    responses:
      '200': {$ref: '#/components/responses/AfterCreate'}
      default: {$ref: '#/components/responses/GenericError'}


/admin/products/{id}:
  get:
    tags:
    - product 
    operationId: admin/ProductController.get
    parameters:
      - $ref: '#/components/parameters/Id'
    responses:
      '200':  {$ref: '#/components/responses/OneProduct'}
      default: {$ref: '#/components/responses/GenericError'}
  delete:
    security: 
      - apiKey: [] 
    description: "Delete product"
    operationId: admin/ProductController.delete
    tags:
    - product 
    parameters:
      - $ref: '#/components/parameters/Id'

    responses: 
      default: {$ref: '#/components/responses/GenericError'}
      '200': {$ref: '#/components/responses/EditOrCreate'}
